# Gunakan image PHP dari Docker Hub
FROM php:7.4-apache

# Set working directory di container
WORKDIR /var/www/html

# Salin file composer dan install dependencies
COPY composer.json composer.lock ./

# Salin seluruh file project Laravel ke working directory di container
COPY . .

# Buat key Laravel
#RUN php artisan key:generate

# Atur permission pada direktori storage dan cache
RUN chmod -R 777 storage bootstrap/cache

# Expose port 80
EXPOSE 80

# Jalankan Apache saat container dijalankan
CMD ["apache2-foreground"]
